config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'
  get "about-us" => "our_school#about_us", :as => "about_us"
  get "history" => "our_school#history", :as => "history"
  get "leadership-team" => "our_school#leadership_team", :as => "leadership_team"
  get "location-and-facilities" => "our_school#location_and_facilities", :as => "location_and_facilities"
  get "our-philosophy" => "our_school#our_philosophy", :as => "our_philosophy"
  get "principals-welcome" => "our_school#principals_welcome", :as => "principals_welcome"
  get "school-policies" => "our_school#school_policies", :as => "school_policies"
  get "video-gallery" => "our_school#video_gallery", :as => "video_gallery"


  get "sport" => "beyond_classroom#sport", :as => "sport"
  get "curriculum" => "beyond_classroom#curriculum", :as => "curriculum"
  get "art" => "beyond_classroom#art", :as => "art"
  get "exchange-program" => "beyond_classroom#exchange_program", :as => "exchange_program"
  get "study-tour" => "beyond_classroom#study_tour", :as => "study_tour"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_beyond_classroom.html.erb
<aside class="col-xl-3 col-lg-4 col-md-4">
  <div class="sticky-top">
    <div class="quick-navs">
      <ul>
        <li class="<%= active_class(sport_path) %>"><%= link_to "Sport", sport_path %></li>
        <li class="<%= active_class(curriculum_path) %>"><%= link_to "Curriculum", curriculum_path %></li>
        <li class="<%= active_class(art_path) %>"><%= link_to "Arts", art_path %></li>
        <li class="<%= active_class(exchange_program_path) %>"><%= link_to "Exchange Program", exchange_program_path %></li>
        <li class="<%= active_class(study_tour_path) %>"><%= link_to "Study Tours", study_tour_path %></li>
      </ul>
    </div>
  </div>

</aside>

app/views/partials/_our_school.html.erb
<aside class="col-xl-3 col-lg-4 col-md-4">
  <div class="sticky-top">
    <div class="quick-navs">
      <ul>
        <li class="<%= active_class(principals_welcome_path) %>"><%= link_to "Principal’s Welcome", principals_welcome_path %></li>
        <li class="<%= active_class(about_us_path) %>"><%= link_to "Why GBS?", about_us_path %></li>
        <li class="<%= active_class(our_philosophy_path) %>"><%= link_to "Our Philosophy", our_philosophy_path %></li>
        <li class="<%= active_class(history_path) %>"><%= link_to "History", history_path %></li>
        <li class="<%= active_class(location_and_facilities_path) %>"><%= link_to "Location & Facilities", location_and_facilities_path %></li>
        <li class="<%= active_class(leadership_team_path) %>"><%= link_to "Leadership Team", leadership_team_path %></li>
        <li class="<%= active_class(school_policies_path) %>"><%= link_to "School Policies", school_policies_path %></li>
        <li class="<%= active_class(video_gallery_path) %>"><%= link_to "Video Gallery", video_gallery_path %></li>
      </ul>
    </div>
  </div>

</aside>